serverAddr =  
serverPort = 7000
auth.token = "123456"

[[visitors]]
type = "sudp"
name = "visitor_pz_udp_16261"
serverName = "pz_udp_16261"
bindAddr = "127.0.0.1"
bindPort = 23333

[[visitors]]
type = "sudp"
name = "visitor_pz_udp_16262"
serverName = "pz_udp_16262"
bindAddr = "127.0.0.1"
bindPort = 23334

