serverAddr = "47.236.117.175" 
serverPort = 7000
auth.token = "123456"
# 设置成新的token，要与proxy的一致

[[visitors]]
type = "xtcp"
name = "visitor_pz_tcp_8766"
serverName = "pz_tcp_8766"
# 设置成新的sk，要与server中ZP_8766_TCP的sk一致
secretKey = "123456"
bindAddr = "127.0.0.1"
bindPort = 8766

[[visitors]]
type = "sudp"
serverName = "pz_udp_8766"
name = "visitor_pz_udp_8766"
# 设置成新的sk，要与server中ZP_8766_UDP的sk一致
secretKey = "123456"
bindAddr = "127.0.0.1"
bindPort = 8766

[[visitors]]
type = "xtcp"
name = "visitor_pz_tcp_16261"
serverName = "pz_tcp_16261"
# 设置成新的sk，要与server中ZP_16261_TCP的sk一致
secretKey = "123456"
bindAddr = "127.0.0.1"
bindPort = 16261

[[visitors]]
type = "sudp"
name = "visitor_pz_udp_16261"
serverName = "pz_udp_16261"
# 设置成新的sk，要与server中ZP_16261_UDP的sk一致
secretKey = "123456"
bindAddr = "127.0.0.1"
bindPort = 16261