serverAddr = 
serverport = 7000
auth.token = "123456"

[[proxies]]
name = "pz_udp_16261"
type = "sudp"
localIP = "127.0.0.1"
localPort = 16261

[[proxies]]
name = "pz_udp_16262"
type = "sudp"
localIP = "127.0.0.1"
localPort = 16262
