serverAddr = "47.236.117.175"
serverport = 7000
auth.token = "123456"

[[proxies]]
name = "pz_udp_16261"
type = "sudp"
localIP = "127.0.0.1"
localPort = 16261

# [[proxies]]
# name = "pz_tcp_16261"
# type = "stcp"
# localIp = "127.0.0.1"
# secretKey = "123456"
# localPort = 16261
# # remotePort = 16261

[[proxies]]
name = "pz_udp_16262"
type = "sudp"
localIP = "127.0.0.1"
localPort = 16262

# [[proxies]]
# name = "pz_tcp_16262"
# type = "stcp"
# localIp = "127.0.0.1"
# secretKey = "123456"
# localPort = 16262
# remotePort = 16262
